baseurl: "/"
title: "Michael S. Collier's Blog"
theme: ["mainroad"]
copyright: "Michael S. Collier"
disqusShortname: "mcollier-blog"
languageCode: "en-us"
# googleAnalytics: "UA-156433646-1"
enableEmoji: true
enableGitInfo: true

params:
  mainSection:
    - post
  intro: true
  headline: "Michael S. Collier"
  subtitle: "I blog about Azure, software engineering, and a few other things."
  copyright: "Michael S. Collier"
  post_meta: ["author", "date", "categories", "translations"]
  readmore: true
  opengraph: true
  shareTwitter: true
  shareFacebook: true
  shareGooglePlus: true
  shareLinkedIn: true
  readingTime: true
  pager: true
  readingTimeText: "Estimated reading time:"
  dateFormat: "Mon, Jan 2, 2006"
  customCSS: ["css/custom.css"]
  style:
    vars:
      highlightColor: "#0078D4"
  sidebar:
    home: "right"
    list: "left"
    single: false
    widgets:
      - "recent"
      - "taglist"
      - "social"
  widgets:
    recent_num: 5
    tags_counter: true
    social:
      twitter: michaelcollier
      github: mcollier
      linkedin: mcollier

services:
  googleAnalytics:
    ID: G-KY6W41KVC7

permalinks:
  post: "/:filename/"

markup:
  highlight:
    codefences: true
    lineNos: true
    style: github

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: About
      url: /page/about
      weight: 2
    - name: Contact
      url: /page/contact
      weight: 3
